### ISSUE TITLE
Issue reproducing the stacked regression

### ISSUE THREAD

**Issue by dyhan316** [HuthLab/encoding-model-scaling-laws#6]
It appears that the provided R matrix for stacked regression have NaN values. For example, for subject 1, the R values 
```
R[81116-1 : 81116+2,0,0]
array([32058.53562594,            nan,            nan])
```

Also, it seems that the "test_preds_whisepr*" files and such are missing for Subjects 1 and 2 (i.e. only subject 3 has the following folder : https://utexas.app.box.com/v/EncodingModelScalingLaws/folder/238580691959)

Could you please provide them?

Or instead, could you just **provide the voxel-wise mean_r2 of the stacked regression model for all subjects? (This is all we need)**

**Comment by RAntonello** [comment]
These values have been added to the box.
